version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Swap node versions
          command: |
            set +e
            wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm install v12
            nvm alias default 12.19.0

            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
          pkg-manager: npm
      - run:
          name: Run Lint (Analyse code for potential errors)
          command: npm run lint
      - run:
          name: Run Formatter (Check Format)
          command: npm run check-format:all
      - run:
          name: Build Project
          command: npm run build

workflows:
  build-and-test: # Name of the workflow, can change it to better match workflow.
    # Inside the workflow, define the jobs want to run.
    jobs:
      - build-and-test
