version: 2.1

orbs:
  node: circleci/node@4.7

jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node:
          steps:
            - run:
                name: Install Project Dependencies
                command: npm install
            - run:
                name: Run Lint (Analyse code for potential errors)
                command: npm run lint
            - run:
                name: Run Formatter (Check Format)
                command: npm run check-format:all
            - run:
                name: Build Project
                command: npm run build

workflows:
  build-and-test: # Name of the workflow, can change it to better match workflow.
    # Inside the workflow, define the jobs want to run.
    jobs:
      - build-and-test
